### ISSUE TITLE
Refactor into standard package format.

### ISSUE THREAD

**Issue by xoviat** [pywin32/pypiwin32#31]
This isn't going to happen anytime soon. Right now, only our setup.py is different from upstream so it's trivial to apply changes. If pywin32 doesn't release for py3.7, then we may consider this. Right now, I expect this issue to remain open for a year or more.

**Comment by bpabel** [comment]
Also wanted to note that the use of `pywin32.pth` to add additional subdirectories to the PYTHONPATH doesn't work when `pypiwin32` isn't installed into a "site-packages` directory.  If for example, `pypiwin32` is installed to a shared location and made available by adding the directory to the PYTHONPATH, the `.pth` file won't be processed unless the directory is also added as a site-directory.

**Comment by xoviat** [comment]
The actual code used to load the DLLs and such is pretty horrible but for now, I'd like to leave some semblance that we are simply a "packaging project;" changing that code would take use too far away from that at this time.
