### ISSUE TITLE
Memleak with repeated WriteFile/ReadFile to named pipe

### ISSUE THREAD

**Issue by dwendt** [pywin32/pypiwin32#68]
Hey,

I'm calling WriteFile and then ReadFile on a named pipe approximately 20000 times, with 20000 different str objects. When the thread completes that task it ends, I call `gc.collect`, and dump the objects hanging around. There's about 3500 new strings that remain uncollected forever each time this loop runs (maybe 
I only created 3500 unique strings in my test, honestly).

Replacing WriteFile/ReadFile with print statements results in no additional strings hanging around, but I cannot replace them individually to test because this relies on a named pipe server sending back a message of course. 

I don't know if ParseTuple mallocs anything that needs to be freed here:
https://github.com/pywin32/pypiwin32/blob/70e91d97d3fe74538b761e0ae0f44ffcb24292a9/win32/src/wincerapi.i#L778

Or if the string allocated here will be properly free'd by the Python GC?
https://github.com/pywin32/pypiwin32/blob/70e91d97d3fe74538b761e0ae0f44ffcb24292a9/win32/src/wincerapi.i#L768

This is on 2.7.13, windows x64.

**Comment by dwendt** [comment]
Apologies, after testing I think this was a misfile.

**Comment by xoviat** [comment]
Honestly I wish Python 2.7 would go away. I mean, you have to expect
problems when you're using a compiler that's from 2008! But apparently
there are still some users out there.

2017-08-18 16:50 GMT-05:00 Ditmar Wendt <notifications@github.com>:
